version: '3'
services:
    test_db:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin-user
            MONGO_INITDB_ROOT_PASSWORD: admin-password
            MONGO_INITDB_DATABASE: family-test
        ports:
            - '27017:27017'
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro # ro = readonly
